name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check formatting
      run: cargo fmt --all -- --check
    
    - name: Run Clippy (disabled error warnings for now)
      run: cargo clippy --all-targets --all-features
    
    - name: Build
      run: cargo build --verbose --all-features
    
    - name: Run tests
      run: cargo test --verbose --all-features
    
    - name: Security audit
      run: |
        cargo install cargo-audit
        cargo audit